{
 "title": "Flight Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum / http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_working_set_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RPS (Запросы в секунду)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}